services:
  - type: web
    name: sistema-quantitativos
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
